version: 2

defaults:
    platform: docker
    plugins:
        vault:
            enabled: True
            secrets:
                - path: secret/services/jenkins/npm/novum-publish
                  keys:
                      token: NPM_TOKEN

workflows:
    npm_publish:
        stages:
            - assert_is_master_branch
            - docker_pull
            - yarn_install
            - build
            - docker_down

    npm_publish_dry_run:
        stages:
            - docker_pull
            - yarn_install
            - build
            - docker_down

stages:
    assert_is_master_branch:
        - bash -c 'if [[ ! $(git diff origin/master) ]]; then echo "Not in master or outdated" exit 1; fi'

    docker_pull:
        - docker-compose pull --ignore-pull-failures

    docker_down:
        - docker-compose down --remove-orphans

    yarn_install:
        - docker-compose run node_mistica_builder yarn

    build:
        - docker-compose run node_mistica_builder yarn build
