name: Release
on:
    workflow_dispatch:
        inputs:
            cliArgs:
                description: 'CLI args'
                required: false
                default: ''
jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.ABEL_GITHUB_TOKEN }}
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: yarn
            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.ABEL_GITHUB_TOKEN }}
                  GH_TOKEN: ${{ secrets.ABEL_GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
                  NPM_CONFIG_USERCONFIG: '.do-not-use-npmrc'
              run: npx semantic-release ${{ github.event.inputs.cliArgs }}
